---
title: "Adaptive Resilience"
format:
  html:
    toc: true
    css: prep/styles.css
execute: 
  warning: false
  message: false
  error: false
  echo: false
editor: visual
---

::: definition_box
**Adaptive resilience** is the extent to which ecosystem actors are regularly learning and adapting to emerging changes in context and evidence, individually and collectively.
:::

[**Finding 14. Deficits in trust, a lack of willingness to compromise, and uneven levels of commitment all pose challenges for ecosystem actors in their efforts to collaborate with others.**]{style="color: #00457c;"}

A non-grantee organization that works with academic and research institutions had issues with partners believing that their way is correct because they are the “custodians of knowledge” and another non-grantee had an issue with partners feeling as though their organizations were in competition.

::: box
For us, what was important, what we found difficult was to convince our partners, since they are higher institutions, they always believed that, they are custodians of knowledge and what they want is what is truly important. I'm saying this because you talked about open discussion, and what worked for us was actually getting to make them understand , bringing them to a common ground. That really worked because when they realized the goals, the objectives, and what we wanted to do, they went out of their way and they work with us to even identify specific participants in all our programs because they believe that these participants will contribute to achieving these goals. The challenge has always been about, bringing people from different institutions to work towards a common goal. That really was problematic. And even on the issue of voice and teeth, it is more or less the same thing for us. \[they don’t understand they have a common goal\] *–Non-Grantee FGD participant*
:::

Similarly, grantees found interagency rivalry between MDAs and issues with organizations taking sole credit or trying to pass blame (if they believe the work could lead to arrest or issues for them) or fear and suspicion of CSOs by MDAs. In another vein, a criminal justice grantee had issues with a partner wanting to take sole ownership of data.

::: box
One of the challenges that we have then was the issue of interagency rivalry among different agencies of government that are responsible for putting in place mechanisms to checkmates the issues of corruption. *-Non-grantee FGD participant*
:::

Similar challenges were noted in the baseline study. Grantees noted that they confronted the slowness inherent in bureaucracy and public resource constraints when trying to engage government partners, and they highlighted the lack of trust among government and civil society which can make it hard to establish and maintain collaborative partnerships.

::: box-left
There's also the challenge so we're working together and then there happens to be a big crisis and then who faces the crisis. Also most organizations will look at it that oh, so if this thing goes to court, I'm the one they would arrest. *-Media and Journalism FGD participant*
:::

Partnerships are challenging. In the event that there's a crisis, which partner is responsible? This dynamic is in the background of partnerships and affects how committed partners are to their arrangement.

[**Finding 15. Network actors leverage deliberate relationship building and communication strategies to adapt to, and overcome, challenges regarding collaboration.**]{style="color: #00457c;"}

FGDs attest to the challenges posed by partnerships, and they also highlighted ways that actors adapted and learned from each other and overcame these challenges. During the baseline study, we found that organizations invested lots of time and deliberate effort in building relationships and trust with their partners. The endline study confirms that this is still valuable time spent.

Specifically, grantees enhanced communication by grounding discussions in the shared goals and objectives of the partnership, emphasize collaboration over competition, focus on how the collaboration can support their work (particularly with government partners), and basic open communication (like asking for help when needed and gently pointing out a mistake to be remedied).

One Criminal Justice grantee highlighted the role of a steering committee in taking ownership over collaborative work in order to relieve any pressure of an individual organization wanting to own the work alone.

::: box
....that steering committee also provided ownership and they know too well that we were not actually engaging for purposes of shaming, but of course we were actually engaging for purposes of deepening, strengthening some of those gaps that we have actually noticed that quickly gave them the level of ownership and confidence. So that particular intelligence steering committee that we set up was actually one of the key success stories that we can actually see ... *-Criminal Justice FGD participant*
:::

A non-grantee organization that works with government used strategic framing for their work to foster trust from their government partners. This was through the use of “knowing and showing” as opposed to “naming and shaming.” This change in perspective allowed the organization to share information with the public about who was responsible for specific public services thereby shining a light on individuals and encouraging proper behavior without causing those individuals to feel they were shamed for any lack of accountability or transparency.

::: box
\[knowing and showing\] gives us an opportunity to sometimes resensitize the actors on the need or what is their responsibility .... they now sit up and so, okay, so it means that the public is aware of what is my statutory responsibility and what I should do. *-Non-grantee FGD participant*
:::
