---
title: "Introduction"
format:
  html:
    toc: true
    embed-resources: true
    css: prep/styles.css
execute: 
  warning: false
  message: false
  error: false
  echo: false
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE)

source(here::here("./prep/prep.r"))
source(here::here("./scripts/00 cleaning script.R"))
source(here::here("./scripts/01 descriptives.R"))
```

# Introduction

The MacArthur Foundation’s Big Bet On Nigeria program supports Nigerian-led efforts to reduce corruption by strengthening accountability, transparency, and participation. A resilient accountability ecosystem—the networks of relationships “between citizens and governing authorities … \[and\] other important actors, including media, private sector, diverse organized citizen groups, and various actors within the state itself” that collectively support social accountability—is essential to the success and sustainability of On Nigeria’s anticorruption programming (for more on accountability ecosystems, see [Halloran’s Accountability Ecosystems: The Evolution of a Keyword)](https://accountabilityresearch.org/accountability-ecosystems-the-evolution-of-a-keyword/).

This social network analysis (SNA) report explores how On Nigeria grantees collaborate with other actors in the broader accountability ecosystem and with each other, the outcomes to which collaboration contributes, and how and to what end collaborative networks might be further strengthened, **to bolster anticorruption efforts**. To do this, the report will investigate the ecosystem elements of collaboration, diversity, adaptive resilience, institutionalization, and scale.[^introduction-1] As a result, this report directly addresses the evolution of the accountability ecosystem (the "trunk" of On Nigeria's theory of change"), and highlights changes since the baseline SNA from 2022.

[^introduction-1]: These elements are contained in the Portfolio Rubrics of the Final Evaluation design.

# Understanding Social Networks

Social network analysis is used to understand interactions. These interactions can be across people, organizations, roads, or items people purchase on the internet. In this case, we are trying to understand the interactions between organizations. In network-speak, the organizations in the network are "nodes" and the connections between nodes are "edges".

### The Baseline Data

For the baseline SNA, the EL Partner distributed an online survey to On Nigeria grantees in all four cohorts (Behavior Change (BC), Criminal Justice (CJ), Joinbodi (JB), and Media and Journalism (MJ)) and their non-grantee (NG) partners, and conducted FGDs with a subset of grantees. Baseline data was collected in June and July 2022. The baseline SNA dataset included 127 organizations and captured 197 unique interactions. [The final report is accessible on the MacArthur Foundation's website.](https://www.macfound.org/media/article_pdfs/sna_report_2022.pdf)

### The Endline Data

The Endline network of On Nigeria grantees and partners consists of `r gorder(g_non)` organizations and `r gsize(g_non)` connections. The relationships between and among these organizations are the focus of this network analysis. The nodes consist of `r length(dat5_non5$grantee[dat5_non5$grantee=="Grantee"])` grantees and `r length(dat5_non5$grantee[dat5_non5$grantee=="Non Grantee"])` non-grantees.

The endline network is made up of different types of organizations. The most common type of organization is a non-governmental organiztion (NGO) which makes up `r ngo_orgs` percent[^introduction-2] of all the organizations. This represents a `r 63 - ngo_orgs` percent decrease in the percent of NGOs in the endline network compared to the baseline network. The next most frequent organization type are Ministries, Departments, and Agencies (MDAs), making up `r govt_orgs` percent[^introduction-3] which is consistent with the baseline network (24 percent). `r private_orgs` percent[^introduction-4] of actors in the network are private businesses, an increase of `r private_orgs-13` percent from the baseline. Finally, international NGOs (INGOs) make up `r ingo_orgs` percent[^introduction-5] of the endline network.

[^introduction-2]: `r length(dat5_non5$desc_org[dat5_non5$desc_org=="NGO"])` organizations

[^introduction-3]: `r length(dat5_non5$desc_org[dat5_non5$desc_org=="MDA"])` organizations

[^introduction-4]: `r length(dat5_non5$desc_org[dat5_non5$desc_org=="Private Business"])` organizations

[^introduction-5]: `r length(dat5_non5$desc_org[dat5_non5$desc_org=="INGO"])` organizations
