---
title: "Methodology"
format:
  html:
    toc: true
    css: prep/styles.css
execute: 
  warning: false
  message: false
  error: false
  echo: false
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE)

source(here::here("./prep/prep.r"))
source(here::here("./scripts/00 cleaning script.R"))
source(here::here("./scripts/01 descriptives.R"))
```

## Overview

In October 2024, the Evaluation and Learning Partner (EL Partner) held a workshop in Abuja, Nigeria with all On Nigeria grantees for the final annual, in-person learning event of On Nigeria 2.0. Grantees represented all four cohorts (Behavior Change, Criminal Justice, JoinBodi, and Media and Journalism). Each grantee completed a survey, in which they identified their primary partners, and in November 2024, the EL Partner followed up with each grantee via survey to identify additional partner relationships. In January 2025, the EL Partner sent a survey to non-grantee organizations that were identified by grantees as connections to develop a more robust network.

To clean, analyze, and visualize the endline network data, the EL Partner used the R programming language. To provide additional context around the network statistics, the EL Partner employed a Monte Carto simulation approach to generate 1,000 similar networks based on the actual network density and the actual number of connections. This provides a point of comparison for the actual network's network statistics.

In addition, the EL Partner mapped the organizations to their respective states on an interactive map of Nigeria to better visualize the geographic make up of the organizations and their connections. A list of R packages used for the analysis is included in Annex 6. This online report was rendered using Quarto.

The survey was supplemented with six focus group discussions (FGDs) with grantees (4 FGDs) and non-grantees (2 FGDs) in February 2025. Respondents all represented voice actors and were primarily from NGOs. There was one INGO represented in the Criminal Justice FGD, six participants represented private businesses (primarily media organizations), and one government entity was represented in the Joinbodi session. In terms of geography, fourteen participants' organizations are based in the XXX, nine were based in YYY, two were from ZZZ, and one each were from FDFD, DDD, RRRR, and LLLL. Six respondents were female, while the rest were male. Finally the cohort breakdown was: four Criminal Justice grantees, eight Joinbodi grantees, seven Media and Journalism grantees, four Behavior Change grantees, and six non-grantees. The FGDs were all conducted remotely over Zoom, and the transcripts were analyzed using CoLoop.

Of the `r gsize(g_non)` connections in the endline network, `r round(reciprocity(g_non)*100, 0)` percent are confirmed, and `r round(100-reciprocity(g_non)*100, 0)` are unconfirmed.[^methodology-1] This represents an increase in confirmed connections of `r round(reciprocity(g_non)*100, 0) - 13` percent. To be certain, this statistic is affected by non-responses. If only one organization in a pair responded to the survey, then the interaction cannot be confirmed. For the endline survey, there was an extra effort made to follow up with grantees and to contact non-grantees, and this is reflected in the increase in confirmed connections.

[^methodology-1]: A confirmed connection means that both organizations in a pair identified the connection, and an unconfirmed connection means that only one organization in a pair identified the connection.

## Limitations

There are limitations to the data. There is a snapshot of data from the baseline (2022) and a snapshot of data from the endline (2024-2025). Since participation was voluntary, there may be gaps in representation, particularly among smaller organizations. The response rates for the endline survey were 69 percent for grantees and 53 percent for non-grantees.[^methodology-2] This compares to response rates of 77 percent of grantees and 56 percent of non-grantees for the baseline report.[^methodology-3]

[^methodology-2]: There were an additional 16 grantee organizations who started the survey but did not provide information on their partnerships.

[^methodology-3]: 49 of 63 grantees responded and 26 of 45 non-grantees responded to the baseline survey.

It is likely that survey fatigue affected responses as well. In addition, each time a new partner was added, it meant that a respondent had to go through the same series of questions again. This likely means that the included partnerships are not exhaustive due to time or an individual respondent's knowledge. On Nigeria subgrantees were not specifically included in the survey sample, although some sub-granting grantees mentioned them as partners. However, the data do not distinguish between non-grantee organizations and On Nigeria subgrantees. Therefore, the data might also understate the depth of connection some organizations represented as non-grantees have to the overall network.

Neither the online survey nor FGDs contained any questions specifically focused on collaboration related to gender equity and social inclusion (GESI) activities or considerations. Data for analysis of this component were based on mentions of GESI made during the FGDs and open-ended survey questions. Thus, the data on this may not provide a complete picture.

Finally, it is important to emphasize that there is no inherent judgment associated with the specific value of any network statistic—they are all context specific: a very high density or centrality score, for example, is not necessarily desirable, as it may not be efficient or effective for every network actor to be connected to all, or even many, others. Rather, collaborations covered in this report should be understood within the context of each network actor’s goals and activities. In an attempt to help the reader understand the network statistics, the EL Partner generated 1,000 similar networks based on the actual network structure and calculated average centrality statistics as a benchmark against which to compare the actual network statistic averages.
